# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1d6d0c56d32070c0a12de72a09d2294"
name = "video-reels-app"
handle = "video-reels-app"
application_url = "https://remix-starter-template.t4taurus.workers.dev/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://remix-starter-template.t4taurus.workers.dev//auth/callback",
 "https://remix-starter-template.t4taurus.workers.dev//auth/shopify/callback",
  "https://remix-starter-template.t4taurus.workers.dev//api/auth/callback"]

[pos]
embedded = false
